name: Build extension and upload on release

on:
  release:
    types: [published]
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install all dependencies
    - name: Install modules
      run: yarn

    # Build artifacts
    - name: Build web extension
      run: yarn run web-ext:build

    # Upload artifacts to release
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'web-ext-artifacts/*.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
