name: Test

# Controls when the action will run. Triggers the workflow on all push and pull_request events
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use NodeJS v14
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Install all dependencies
      - name: Install modules
        run: yarn

      # Run JEST test suite
      - name: Run tests
        run: yarn run test

      # Lint JS
      - name: Lint JS
        run: yarn run lint:js

      # Lint CSS
      - name: Lint CSS
        run: yarn run lint:css

      # Lint extension, for Firefox build only
      - name: Lint extension for Firefox build
        run: yarn run build && yarn run lint:ext
